@ToDoList.Api_HostAddress = http://localhost:5112

GET {{ToDoList.Api_HostAddress}}/api/Todo

###

POST {{ToDoList.Api_HostAddress}}/api/Todo
Content-Type: application/json

{
  "title": "Learn Dependency Injection",
  "description": "Understand DI in ASP.NET Core",
  "deadline": "2026-10-02T00:00:00Z"
}
